name: Publish to npm

on:
  push:
    branches:
      - master
    paths:
      - "package.json"
      - "src/**"
      - ".github/workflows/publish.yml"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: "20"
      - run: npm install
      - run: npm run build
      - run: npm publish --access public --provenance
